services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - document_storage:/app/document_storage
      - chroma_db:/app/chroma_db
      - db_data:/app/db
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENVIRONMENT=development
      - SECRET_KEY=your-secret-key-change-this-in-production
    depends_on:
      - ollama
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped
    command: npm start

volumes:
  document_storage:
  chroma_db:
  db_data:
  ollama_data:
